// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbokuytxovfaggpxawvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJib2t1eXR4b3ZmYWdncHhhd3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODIwMzAsImV4cCI6MjA1Nzk1ODAzMH0.vSYpjfx_Cr1mCnZDHLdAkquZqgjBqV7NOBQN1QtGuKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);